project:
  type: website
  output-dir: docs

website:
  title: "Melinda Higgins"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resources.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
    page-layout: full

editor: visual

